"""001_foreign_keys

Revision ID: 10f427edc2b7
Revises: fad18eddf717
Create Date: 2019-03-29 19:55:50.886419

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '10f427edc2b7'
down_revision = 'fad18eddf717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('chat_id', sa.Integer(), nullable=True))
    op.add_column('attachments', sa.Column('message_id', sa.Integer(), nullable=True))
    op.add_column('attachments', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'attachments', 'chats', ['chat_id'], ['chat_id'])
    op.create_foreign_key(None, 'attachments', 'messages', ['message_id'], ['message_id'])
    op.create_foreign_key(None, 'attachments', 'users', ['user_id'], ['user_id'])
    op.add_column('chats', sa.Column('last_message_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chats', 'messages', ['last_message_id'], ['message_id'])
    op.add_column('members', sa.Column('chat_id', sa.Integer(), nullable=False))
    op.add_column('members', sa.Column('last_read_message_id', sa.Integer(), nullable=True))
    op.add_column('members', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'members', 'messages', ['last_read_message_id'], ['message_id'])
    op.create_foreign_key(None, 'members', 'chats', ['chat_id'], ['chat_id'])
    op.create_foreign_key(None, 'members', 'users', ['user_id'], ['user_id'])
    op.add_column('messages', sa.Column('chat_id', sa.Integer(), nullable=False))
    op.add_column('messages', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'messages', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['chat_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'user_id')
    op.drop_column('messages', 'chat_id')
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.drop_column('members', 'user_id')
    op.drop_column('members', 'last_read_message_id')
    op.drop_column('members', 'chat_id')
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_column('chats', 'last_message_id')
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.drop_column('attachments', 'user_id')
    op.drop_column('attachments', 'message_id')
    op.drop_column('attachments', 'chat_id')
    # ### end Alembic commands ###
