"""004_user_fixes

Revision ID: 445cdbfa1595
Revises: af28984e9b1e
Create Date: 2019-03-23 00:35:53.990956

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '445cdbfa1595'
down_revision = 'af28984e9b1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('password', sqlalchemy_utils.types.password.PasswordType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    op.drop_column('users', 'birth_date')
    # ### end Alembic commands ###
