"""005_members_fixes

Revision ID: 6f904a08fe27
Revises: 9292b5e389c4
Create Date: 2019-05-09 19:58:17.536224

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '6f904a08fe27'
down_revision = '9292b5e389c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('members_last_read_message_id_fkey', 'members', type_='foreignkey')
    op.drop_column('members', 'last_read_message_id')
    op.drop_column('members', 'new_messages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('new_messages', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('members', sa.Column('last_read_message_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('members_last_read_message_id_fkey', 'members', 'messages', ['last_read_message_id'], ['message_id'])
    # ### end Alembic commands ###
