"""001_fix_foreign_keys

Revision ID: 89bef624f8d1
Revises: 8da2d5af66ee
Create Date: 2019-03-14 20:21:55.864025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89bef624f8d1'
down_revision = '8da2d5af66ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'attachments', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key(None, 'attachments', 'chats', ['chat_id'], ['chat_id'])
    op.create_foreign_key(None, 'attachments', 'messages', ['message_id'], ['message_id'])
    op.create_foreign_key(None, 'chats', 'messages', ['last_message_id'], ['message_id'])
    op.create_foreign_key(None, 'members', 'chats', ['chat_id'], ['chat_id'])
    op.create_foreign_key(None, 'members', 'messages', ['last_read_message_id'], ['message_id'])
    op.create_foreign_key(None, 'members', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key(None, 'messages', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['chat_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    # ### end Alembic commands ###
