"""000_init_tables

Revision ID: 8da2d5af66ee
Revises: 
Create Date: 2019-03-14 19:23:07.251003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8da2d5af66ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('last_message_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_chats_chatname'), 'chats', ['chatname'], unique=False)
    op.drop_column('chats', 'last_message')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_constraint('users_username_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.add_column('chats', sa.Column('last_message', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_chats_chatname'), table_name='chats')
    op.drop_column('chats', 'last_message_id')
    # ### end Alembic commands ###
