"""003_attachment_fix

Revision ID: af28984e9b1e
Revises: c8d182e993d2
Create Date: 2019-03-21 16:11:01.494179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af28984e9b1e'
down_revision = 'c8d182e993d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('attachment_url', sa.String(length=500), nullable=False))
    op.drop_column('attachments', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('url', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.drop_column('attachments', 'attachment_url')
    # ### end Alembic commands ###
