"""002_chat_fix

Revision ID: c8d182e993d2
Revises: 89bef624f8d1
Create Date: 2019-03-21 14:59:41.231773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8d182e993d2'
down_revision = '89bef624f8d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('chat_title', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_chats_chat_title'), 'chats', ['chat_title'], unique=False)
    op.drop_index('ix_chats_chatname', table_name='chats')
    op.create_index(op.f('ix_chats_chatname'), 'chats', ['chatname'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chats_chatname'), table_name='chats')
    op.create_index('ix_chats_chatname', 'chats', ['chatname'], unique=False)
    op.drop_index(op.f('ix_chats_chat_title'), table_name='chats')
    op.drop_column('chats', 'chat_title')
    # ### end Alembic commands ###
