"""001 database fix 

Revision ID: d086b18017e9
Revises: fd0987c64a99
Create Date: 2019-03-12 21:41:12.679434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd086b18017e9'
down_revision = 'fd0987c64a99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('chats', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('members', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('messages', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('messages', 'updated_at')
    op.drop_column('members', 'updated_at')
    op.drop_column('chats', 'updated_at')
    op.drop_column('attachments', 'updated_at')
    # ### end Alembic commands ###
