"""008_chat_fixes

Revision ID: f85901943c9b
Revises: fe779a8be535
Create Date: 2019-05-10 18:16:53.509824

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'f85901943c9b'
down_revision = 'fe779a8be535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'updated_at')
    # ### end Alembic commands ###
