"""007_chat_fixes

Revision ID: fe779a8be535
Revises: 3e9f9aaa8dce
Create Date: 2019-05-10 10:22:15.785630

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fe779a8be535'
down_revision = '3e9f9aaa8dce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'chats', 'users', ['creator_id'], ['user_id'])
    op.drop_column('chats', 'updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_column('chats', 'creator_id')
    # ### end Alembic commands ###
